In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/yahyafuat/datathon/sample_submission.csv
/kaggle/input/datasets/yahyafuat/datathon/train_seyma_cleaned.csv
/kaggle/input/datasets/yahyafuat/datathon/test_seyma_cleaned.csv
/kaggle/input/datasets/yahyafuat/datathon/test_x.csv
/kaggle/input/datasets/yahyafuat/datathon/train.csv

In [2]:
train = pd.read_csv('/kaggle/input/datasets/yahyafuat/datathon/train.csv')
train.head()

,id,yas,cinsiyet,meslek,vucut_kitle_indeksi,ulke,rem_yuzdesi,derin_uyku_yuzdesi,uykuya_dalma_suresi_dk,gecelik_uyanma_sayisi,...,stres_skoru,gunluk_calisma_saati,kronotip,ruh_sagligi_durumu,dinlenik_nabiz_bpm,oda_sicakligi_celsius,hafta_sonu_uyku_farki_saat,mevsim,gun_tipi,bilissel_performans_skoru
0,1,34,Erkek,Saglik Personeli,31.470103,Cin,14.431210,14.645436,27,7,...,9.922976,10.045274,Sabah insani,Anksiyete ve depresyon,78,18.962436,-0.074140,Sonbahar-Kis,Hafta ici,0.136441
1,2,32,Kadin,Muhendis,30.981394,Amerika,21.771870,27.220360,20,4,...,6.626400,6.319245,Gece insani,Saglikli,76,21.225666,0.942672,Sonbahar-Kis,Hafta ici,5.848312
2,3,39,Erkek,Ev Hanimi,21.533898,Spain,18.178857,25.530104,33,7,...,6.093566,3.824463,Notr,Depresyon,66,18.482409,1.239886,Ilkbahar-Yaz,Hafta sonu,6.828276
3,4,40,Kadin,Egitimci,23.310749,Yeni Zelanda,21.438151,15.891188,21,2,...,3.168185,4.597316,Gece insani,Saglikli,60,21.862235,0.727695,Sonbahar-Kis,Hafta sonu,8.144649
4,5,36,Kadin,NaN,NaN,Portekiz,25.468018,16.356738,21,8,...,7.198574,3.189120,Notr,Anksiyete ve depresyon,74,19.223195,-0.223402,Sonbahar-Kis,Hafta ici,0.431423

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56000 entries, 0 to 55999
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           56000 non-null  int64
 1   yas                          56000 non-null  int64
 2   cinsiyet                     56000 non-null  object
 3   meslek                       54622 non-null  object
 4   vucut_kitle_indeksi          54248 non-null  float64
 5   ulke                         56000 non-null  object
 6   rem_yuzdesi                  56000 non-null  float64
 7   derin_uyku_yuzdesi           56000 non-null  float64
 8   uykuya_dalma_suresi_dk       56000 non-null  int64
 9   gecelik_uyanma_sayisi        56000 non-null  int64
 10  uyku_oncesi_kafein_mg        54537 non-null  float64
 11  uyku_oncesi_ekran_suresi_dk  56000 non-null  int64
 12  gunluk_adim_sayisi           56000 non-null  int64
 13  sekerleme_suresi_dk          56000 non-null  int64
 14  stres_skoru                  54285 non-null  float64
 15  gunluk_calisma_saati         56000 non-null  float64
 16  kronotip                     54032 non-null  object
 17  ruh_sagligi_durumu           54904 non-null  object
 18  dinlenik_nabiz_bpm           56000 non-null  int64
 19  oda_sicakligi_celsius        56000 non-null  float64
 20  hafta_sonu_uyku_farki_saat   56000 non-null  float64
 21  mevsim                       56000 non-null  object
 22  gun_tipi                     56000 non-null  object
 23  bilissel_performans_skoru    56000 non-null  float64
dtypes: float64(9), int64(8), object(7)
memory usage: 10.3+ MB

In [4]:
train.describe()

,id,yas,vucut_kitle_indeksi,rem_yuzdesi,derin_uyku_yuzdesi,uykuya_dalma_suresi_dk,gecelik_uyanma_sayisi,uyku_oncesi_kafein_mg,uyku_oncesi_ekran_suresi_dk,gunluk_adim_sayisi,sekerleme_suresi_dk,stres_skoru,gunluk_calisma_saati,dinlenik_nabiz_bpm,oda_sicakligi_celsius,hafta_sonu_uyku_farki_saat,bilissel_performans_skoru
count,56000.000000,56000.000000,54248.000000,56000.000000,56000.000000,56000.000000,56000.000000,54537.000000,56000.000000,56000.000000,56000.000000,54285.000000,56000.000000,56000.000000,56000.000000,56000.000000,56000.000000
mean,28000.500000,34.714446,26.273651,20.233500,20.246063,20.107536,3.344929,42.110952,63.511446,7493.197554,15.432875,5.741407,7.156456,66.603214,20.531263,1.199050,5.913096
std,16165.951874,11.052508,4.495138,3.442993,4.300421,8.063278,2.034618,72.154159,44.590737,3462.699361,21.104672,1.624985,3.469731,7.353174,2.903317,0.790899,2.231759
min,1.000000,18.000000,16.000000,10.000000,5.000000,1.000000,0.000000,0.000000,2.000000,500.000000,0.000000,1.000000,0.000000,45.000000,15.000000,-1.000000,0.000000
25%,14000.750000,26.000000,23.175279,17.951724,17.337866,14.000000,2.000000,0.000000,30.000000,5042.000000,0.000000,4.761271,4.765942,62.000000,18.457240,0.660030,4.397431
50%,28000.500000,33.000000,26.225806,20.302218,20.292151,20.000000,3.000000,3.000000,51.000000,7426.000000,2.000000,5.824014,7.360860,67.000000,20.487456,1.202921,6.032249
75%,42000.250000,42.000000,29.321503,22.598180,23.227117,25.000000,5.000000,77.000000,84.000000,9876.000000,30.000000,6.837436,9.684531,72.000000,22.522152,1.743940,7.574980
max,56000.000000,69.000000,45.000000,30.000000,30.000000,58.000000,8.000000,400.000000,180.000000,20000.000000,115.000000,10.000000,18.000000,97.000000,28.000000,3.000000,10.000000

In [5]:
missing = train.isnull().sum()
missing_pct = (missing / len(train) * 100).round(2)

missing_df = pd.DataFrame({
    'missing_count': missing,
    'missing_pct': missing_pct
}).query('missing_count > 0').sort_values('missing_pct', ascending=False)

print(missing_df)

                       missing_count  missing_pct
kronotip                        1968         3.51
vucut_kitle_indeksi             1752         3.13
stres_skoru                     1715         3.06
uyku_oncesi_kafein_mg           1463         2.61
meslek                          1378         2.46
ruh_sagligi_durumu              1096         1.96

In [6]:
print("Duplicate rows:", train.duplicated().sum())
print("Duplicate IDs:", train['id'].duplicated().sum())

Duplicate rows: 0
Duplicate IDs: 0

In [7]:
cat_cols = ['cinsiyet', 'meslek', 'ulke', 'kronotip', 'ruh_sagligi_durumu', 'mevsim', 'gun_tipi']

for col in cat_cols:
    print(f"\n--- {col} ---")
    print(train[col].value_counts(dropna=False))

--- cinsiyet ---
cinsiyet
Kadin    28676
Erkek    27324
Name: count, dtype: int64

--- meslek ---
meslek
Saglik Personeli               9842
Ogrenci                        8132
Muhendis                       6533
Yonetici                       4454
Egitimci                       4395
Satis ve Pazarlama Calisani    3899
Serbest Calisan                3812
Lojistik Calisani              3811
Emekli                         3778
Ev Hanimi                      3224
Lawyer                         2742
NaN                            1378
Name: count, dtype: int64

--- ulke ---
ulke
Ingiltere       11324
Cin              9989
Guney Kore       4459
Amerika          4447
Arjantin         3973
Fransa           3440
Ispanya          2823
Isvec            2798
Yeni Zelanda     2777
Portekiz         2204
South Korea      2189
Mexico           2165
Netherlands      1707
Spain            1139
Sweden            566
Name: count, dtype: int64

--- kronotip ---
kronotip
Notr            24594
Gece insani     15938
Sabah insani    13500
NaN              1968
Name: count, dtype: int64

--- ruh_sagligi_durumu ---
ruh_sagligi_durumu
Saglikli                  38365
Anksiyete                  8270
Depresyon                  5504
Anksiyete ve depresyon     2765
NaN                        1096
Name: count, dtype: int64

--- mevsim ---
mevsim
Ilkbahar-Yaz    28143
Sonbahar-Kis    27857
Name: count, dtype: int64

--- gun_tipi ---
gun_tipi
Hafta ici     40052
Hafta sonu    15948
Name: count, dtype: int64

In [8]:
# Fix ulke
ulke_map = {
    'South Korea': 'Guney Kore',
    'Spain': 'Ispanya',
    'Sweden': 'Isvec',
    'Mexico': 'Meksika',
    'Netherlands': 'Hollanda'
}
train['ulke'] = train['ulke'].replace(ulke_map)

# Fix meslek
train['meslek'] = train['meslek'].replace({'Lawyer': 'Avukat'})

# Verify
print(train['ulke'].value_counts())
print("\n", train['meslek'].value_counts(dropna=False))

ulke
Ingiltere       11324
Cin              9989
Guney Kore       6648
Amerika          4447
Arjantin         3973
Ispanya          3962
Fransa           3440
Isvec            3364
Yeni Zelanda     2777
Portekiz         2204
Meksika          2165
Hollanda         1707
Name: count, dtype: int64

 meslek
Saglik Personeli               9842
Ogrenci                        8132
Muhendis                       6533
Yonetici                       4454
Egitimci                       4395
Satis ve Pazarlama Calisani    3899
Serbest Calisan                3812
Lojistik Calisani              3811
Emekli                         3778
Ev Hanimi                      3224
Avukat                         2742
NaN                            1378
Name: count, dtype: int64

In [9]:
num_cols = ['yas', 'vucut_kitle_indeksi', 'rem_yuzdesi', 'derin_uyku_yuzdesi',
            'uykuya_dalma_suresi_dk', 'gecelik_uyanma_sayisi', 'uyku_oncesi_kafein_mg',
            'uyku_oncesi_ekran_suresi_dk', 'gunluk_adim_sayisi', 'sekerleme_suresi_dk',
            'stres_skoru', 'gunluk_calisma_saati', 'dinlenik_nabiz_bpm',
            'oda_sicakligi_celsius', 'hafta_sonu_uyku_farki_saat']

for col in num_cols:
    q1 = train[col].quantile(0.25)
    q3 = train[col].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    non_null = train[col].count()
    outliers = train[(train[col] < lower) | (train[col] > upper)][col].count()
    outlier_pct = (outliers / non_null * 100)
    print(f"{col:35s} | min: {train[col].min():7.2f} | max: {train[col].max():7.2f} | outliers: {outliers:4d} ({outlier_pct:.2f}%)")

yas                                 | min:   18.00 | max:   69.00 | outliers:  184 (0.33%)
vucut_kitle_indeksi                 | min:   16.00 | max:   45.00 | outliers:  173 (0.32%)
rem_yuzdesi                         | min:   10.00 | max:   30.00 | outliers:  420 (0.75%)
derin_uyku_yuzdesi                  | min:    5.00 | max:   30.00 | outliers:  235 (0.42%)
uykuya_dalma_suresi_dk              | min:    1.00 | max:   58.00 | outliers:  531 (0.95%)
gecelik_uyanma_sayisi               | min:    0.00 | max:    8.00 | outliers:    0 (0.00%)
uyku_oncesi_kafein_mg               | min:    0.00 | max:  400.00 | outliers: 3360 (6.16%)
uyku_oncesi_ekran_suresi_dk         | min:    2.00 | max:  180.00 | outliers: 3290 (5.88%)
gunluk_adim_sayisi                  | min:  500.00 | max: 20000.00 | outliers:  166 (0.30%)
sekerleme_suresi_dk                 | min:    0.00 | max:  115.00 | outliers:  505 (0.90%)
stres_skoru                         | min:    1.00 | max:   10.00 | outliers:  986 (1.82%)
gunluk_calisma_saati                | min:    0.00 | max:   18.00 | outliers:   18 (0.03%)
dinlenik_nabiz_bpm                  | min:   45.00 | max:   97.00 | outliers:  300 (0.54%)
oda_sicakligi_celsius               | min:   15.00 | max:   28.00 | outliers:    0 (0.00%)
hafta_sonu_uyku_farki_saat          | min:   -1.00 | max:    3.00 | outliers:  120 (0.21%)

In [10]:
cols_to_check = ['uyku_oncesi_kafein_mg', 'uyku_oncesi_ekran_suresi_dk', 
                 'stres_skoru', 'uykuya_dalma_suresi_dk', 'sekerleme_suresi_dk']

for col in cols_to_check:
    print(f"\n--- {col} ---")
    print(train[col].describe())
    print(f"Values > 99th percentile: {train[col].quantile(0.99):.2f}")

--- uyku_oncesi_kafein_mg ---
count    54537.000000
mean        42.110952
std         72.154159
min          0.000000
25%          0.000000
50%          3.000000
75%         77.000000
max        400.000000
Name: uyku_oncesi_kafein_mg, dtype: float64
Values > 99th percentile: 304.00

--- uyku_oncesi_ekran_suresi_dk ---
count    56000.000000
mean        63.511446
std         44.590737
min          2.000000
25%         30.000000
50%         51.000000
75%         84.000000
max        180.000000
Name: uyku_oncesi_ekran_suresi_dk, dtype: float64
Values > 99th percentile: 180.00

--- stres_skoru ---
count    54285.000000
mean         5.741407
std          1.624985
min          1.000000
25%          4.761271
50%          5.824014
75%          6.837436
max         10.000000
Name: stres_skoru, dtype: float64
Values > 99th percentile: 9.24

--- uykuya_dalma_suresi_dk ---
count    56000.000000
mean        20.107536
std          8.063278
min          1.000000
25%         14.000000
50%         20.000000
75%         25.000000
max         58.000000
Name: uykuya_dalma_suresi_dk, dtype: float64
Values > 99th percentile: 41.00

--- sekerleme_suresi_dk ---
count    56000.000000
mean        15.432875
std         21.104672
min          0.000000
25%          0.000000
50%          2.000000
75%         30.000000
max        115.000000
Name: sekerleme_suresi_dk, dtype: float64
Values > 99th percentile: 74.00

In [11]:
for col in ['vucut_kitle_indeksi', 'stres_skoru', 'uyku_oncesi_kafein_mg']:
    print(f"{col} — skewness: {train[col].skew():.3f}")

vucut_kitle_indeksi — skewness: 0.078
stres_skoru — skewness: -0.341
uyku_oncesi_kafein_mg — skewness: 2.295

In [12]:
# Numeric
train['vucut_kitle_indeksi'] = train['vucut_kitle_indeksi'].fillna(train['vucut_kitle_indeksi'].mean())
train['stres_skoru'] = train['stres_skoru'].fillna(train['stres_skoru'].mean())
train['uyku_oncesi_kafein_mg'] = train['uyku_oncesi_kafein_mg'].fillna(train['uyku_oncesi_kafein_mg'].median())

# Categorical
# Categorical
train['kronotip'] = train['kronotip'].fillna('Bilinmiyor')
train['ruh_sagligi_durumu'] = train['ruh_sagligi_durumu'].fillna('Bilinmiyor')
train['meslek'] = train['meslek'].fillna(train['meslek'].mode()[0])

# Verify
print(train.isnull().sum().sum())

0

In [13]:
print(train['bilissel_performans_skoru'].describe())
print(f"\nSkewness: {train['bilissel_performans_skoru'].skew():.3f}")
print(f"Kurtosis: {train['bilissel_performans_skoru'].kurt():.3f}")

count    56000.000000
mean         5.913096
std          2.231759
min          0.000000
25%          4.397431
50%          6.032249
75%          7.574980
max         10.000000
Name: bilissel_performans_skoru, dtype: float64

Skewness: -0.289
Kurtosis: -0.434

In [14]:
test = pd.read_csv('/kaggle/input/datasets/yahyafuat/datathon/test_x.csv')
test.head()

,id,yas,cinsiyet,meslek,vucut_kitle_indeksi,ulke,rem_yuzdesi,derin_uyku_yuzdesi,uykuya_dalma_suresi_dk,gecelik_uyanma_sayisi,...,sekerleme_suresi_dk,stres_skoru,gunluk_calisma_saati,kronotip,ruh_sagligi_durumu,dinlenik_nabiz_bpm,oda_sicakligi_celsius,hafta_sonu_uyku_farki_saat,mevsim,gun_tipi
0,1,42,Erkek,Saglik Personeli,29.728724,Ingiltere,21.691917,23.990157,21,5,...,0,6.349196,9.419561,Gece insani,Depresyon,82,21.627129,1.716161,Ilkbahar-Yaz,Hafta sonu
1,2,26,Kadin,Serbest Calisan,32.865996,Cin,22.090624,18.231963,34,5,...,0,NaN,8.574199,Gece insani,Saglikli,66,27.835934,1.482283,Ilkbahar-Yaz,Hafta ici
2,3,21,Erkek,Lojistik Calisani,24.438264,Cin,19.488438,16.695363,17,4,...,52,6.715192,10.519017,Notr,Depresyon,63,20.252258,1.981034,Sonbahar-Kis,Hafta ici
3,4,61,Kadin,Saglik Personeli,23.275057,Cin,26.831092,21.762040,29,2,...,2,5.633400,9.814789,Gece insani,Saglikli,71,17.680971,0.589750,Sonbahar-Kis,Hafta ici
4,5,26,Kadin,Saglik Personeli,24.815531,Ingiltere,16.271522,18.153212,15,4,...,0,7.953794,9.308398,Sabah insani,Saglikli,53,23.698979,0.622211,Ilkbahar-Yaz,Hafta ici

In [15]:
print("TEST shape:", test.shape)
test.info()

TEST shape: (24000, 23)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24000 entries, 0 to 23999
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           24000 non-null  int64
 1   yas                          24000 non-null  int64
 2   cinsiyet                     24000 non-null  object
 3   meslek                       23378 non-null  object
 4   vucut_kitle_indeksi          23352 non-null  float64
 5   ulke                         24000 non-null  object
 6   rem_yuzdesi                  24000 non-null  float64
 7   derin_uyku_yuzdesi           24000 non-null  float64
 8   uykuya_dalma_suresi_dk       24000 non-null  int64
 9   gecelik_uyanma_sayisi        24000 non-null  int64
 10  uyku_oncesi_kafein_mg        23303 non-null  float64
 11  uyku_oncesi_ekran_suresi_dk  24000 non-null  int64
 12  gunluk_adim_sayisi           24000 non-null  int64
 13  sekerleme_suresi_dk          24000 non-null  int64
 14  stres_skoru                  23235 non-null  float64
 15  gunluk_calisma_saati         24000 non-null  float64
 16  kronotip                     23168 non-null  object
 17  ruh_sagligi_durumu           23496 non-null  object
 18  dinlenik_nabiz_bpm           24000 non-null  int64
 19  oda_sicakligi_celsius        24000 non-null  float64
 20  hafta_sonu_uyku_farki_saat   24000 non-null  float64
 21  mevsim                       24000 non-null  object
 22  gun_tipi                     24000 non-null  object
dtypes: float64(8), int64(8), object(7)
memory usage: 4.2+ MB

In [16]:
# Fix ulke
test['ulke'] = test['ulke'].replace(ulke_map)

# Fix meslek
test['meslek'] = test['meslek'].replace({'Lawyer': 'Avukat'})

# Numeric imputation — using train statistics!
test['vucut_kitle_indeksi'] = test['vucut_kitle_indeksi'].fillna(train['vucut_kitle_indeksi'].mean())
test['stres_skoru'] = test['stres_skoru'].fillna(train['stres_skoru'].mean())
test['uyku_oncesi_kafein_mg'] = test['uyku_oncesi_kafein_mg'].fillna(train['uyku_oncesi_kafein_mg'].median())

# Categorical imputation — using train mode!
test['kronotip'] = test['kronotip'].fillna('Bilinmiyor')
test['ruh_sagligi_durumu'] = test['ruh_sagligi_durumu'].fillna('Bilinmiyor')
test['meslek'] = test['meslek'].fillna(train['meslek'].mode()[0])

# Verify
print(test.isnull().sum().sum())
print(test['ulke'].value_counts())
print(test['meslek'].value_counts(dropna=False))

0
ulke
Ingiltere       4730
Cin             4279
Guney Kore      2958
Amerika         1921
Arjantin        1777
Ispanya         1633
Fransa          1457
Isvec           1419
Yeni Zelanda    1184
Portekiz        1008
Meksika          905
Hollanda         729
Name: count, dtype: int64
meslek
Saglik Personeli               4808
Ogrenci                        3446
Muhendis                       2904
Egitimci                       1849
Yonetici                       1848
Lojistik Calisani              1688
Emekli                         1681
Serbest Calisan                1656
Satis ve Pazarlama Calisani    1581
Ev Hanimi                      1337
Avukat                         1202
Name: count, dtype: int64

# Şeyma'nın veri setiyle değiştir

In [17]:
test = pd.read_csv("/kaggle/input/datasets/yahyafuat/datathon/test_seyma_cleaned.csv")
train = pd.read_csv("/kaggle/input/datasets/yahyafuat/datathon/train_seyma_cleaned.csv")

In [18]:
# Sleep Quality Features
train['toplam_uyku_yuzdesi'] = train['rem_yuzdesi'] + train['derin_uyku_yuzdesi']
train['uyku_kalitesi_orani'] = train['toplam_uyku_yuzdesi'] / train['uykuya_dalma_suresi_dk']
train['gece_bolunme_skoru'] = train['gecelik_uyanma_sayisi'] * train['uykuya_dalma_suresi_dk']
train['stres_nabiz_etkilesimi'] = train['stres_skoru'] * train['dinlenik_nabiz_bpm']
train['saglik_skoru'] = train['gunluk_adim_sayisi'] / (train['stres_skoru'] + 1)
train['kafein_ekran_etkilesimi'] = train['uyku_oncesi_kafein_mg'] * train['uyku_oncesi_ekran_suresi_dk']
train['yasam_dengesi'] = train['gunluk_calisma_saati'] / (train['sekerleme_suresi_dk'] + 1)

# Apply same to test
test['toplam_uyku_yuzdesi'] = test['rem_yuzdesi'] + test['derin_uyku_yuzdesi']
test['uyku_kalitesi_orani'] = test['toplam_uyku_yuzdesi'] / test['uykuya_dalma_suresi_dk']
test['gece_bolunme_skoru'] = test['gecelik_uyanma_sayisi'] * test['uykuya_dalma_suresi_dk']
test['stres_nabiz_etkilesimi'] = test['stres_skoru'] * test['dinlenik_nabiz_bpm']
test['saglik_skoru'] = test['gunluk_adim_sayisi'] / (test['stres_skoru'] + 1)
test['kafein_ekran_etkilesimi'] = test['uyku_oncesi_kafein_mg'] * test['uyku_oncesi_ekran_suresi_dk']
test['yasam_dengesi'] = test['gunluk_calisma_saati'] / (test['sekerleme_suresi_dk'] + 1)

print(train.shape, test.shape)
# Cap AFTER both train and test features are created
for col in ['kafein_ekran_etkilesimi', 'gece_bolunme_skoru', 'uyku_kalitesi_orani']:
    upper = train[col].quantile(0.99)
    train[col] = train[col].clip(upper=upper)
    test[col] = test[col].clip(upper=upper)

print(train.shape, test.shape)

(56000, 31) (24000, 30)
(56000, 31) (24000, 30)

In [19]:
cols_to_check = ['kafein_ekran_etkilesimi', 'gece_bolunme_skoru', 'uyku_kalitesi_orani']

for col in cols_to_check:
    print(f"\n--- {col} ---")
    print(f"Mean: {train[col].mean():.3f}")
    print(f"Std: {train[col].std():.3f}")
    print(f"99th percentile: {train[col].quantile(0.99):.3f}")
    print(f"Max: {train[col].max():.3f}")

--- kafein_ekran_etkilesimi ---
Mean: 2555.868
Std: 5134.415
99th percentile: 27933.686
Max: 27935.760

--- gece_bolunme_skoru ---
Mean: 67.371
Std: 51.034
99th percentile: 232.000
Max: 232.000

--- uyku_kalitesi_orani ---
Mean: 2.507
Std: 1.658
99th percentile: 12.010
Max: 12.010

In [20]:
cat_cols = train.select_dtypes(include='object').columns.tolist()
print(cat_cols)

['cinsiyet', 'meslek', 'ulke', 'kronotip', 'ruh_sagligi_durumu', 'mevsim', 'gun_tipi']

# Encoding

In [21]:
from sklearn.model_selection import KFold
import numpy as np

# Binary encoding
binary_map = {
    'cinsiyet': {'Kadin': 0, 'Erkek': 1},
    'mevsim': {'Ilkbahar-Yaz': 0, 'Sonbahar-Kis': 1},
    'gun_tipi': {'Hafta ici': 0, 'Hafta sonu': 1}
}

# Ordinal encoding
ordinal_map = {
    'kronotip': {'Bilinmiyor': -1, 'Sabah insani': 0, 'Notr': 1, 'Gece insani': 2},
    'ruh_sagligi_durumu': {'Bilinmiyor': -1, 'Saglikli': 0, 'Anksiyete': 1, 'Depresyon': 2, 'Anksiyete ve depresyon': 3}
}

for col, mapping in {**binary_map, **ordinal_map}.items():
    train[col] = train[col].map(mapping)
    test[col] = test[col].map(mapping)

# Target encoding for meslek and ulke using KFold to avoid leakage
kf = KFold(n_splits=5, shuffle=True, random_state=42)

for col in ['meslek', 'ulke']:
    train[f'{col}_target'] = 0.0
    for train_idx, val_idx in kf.split(train):
        mean_map = train.iloc[train_idx].groupby(col)['bilissel_performans_skoru'].mean()
        train.loc[train.index[val_idx], f'{col}_target'] = train.iloc[val_idx][col].map(mean_map)
    
    # For test use full train mean
    test[f'{col}_target'] = test[col].map(train.groupby(col)['bilissel_performans_skoru'].mean())
    
    # Drop original column
    train = train.drop(columns=[col])
    test = test.drop(columns=[col])

print(train.shape, test.shape)
print(train.dtypes.value_counts())

(56000, 31) (24000, 30)
float64    19
int64      12
Name: count, dtype: int64

# An old method

In [22]:
"""
# Convert bool columns to int
bool_cols = train.select_dtypes(include='bool').columns.tolist()
train[bool_cols] = train[bool_cols].astype(int)
test[bool_cols] = test[bool_cols].astype(int)

# Verify
print(train.shape, test.shape)
print(train.dtypes.value_counts())
"""

"\n# Convert bool columns to int\nbool_cols = train.select_dtypes(include='bool').columns.tolist()\ntrain[bool_cols] = train[bool_cols].astype(int)\ntest[bool_cols] = test[bool_cols].astype(int)\n\n# Verify\nprint(train.shape, test.shape)\nprint(train.dtypes.value_counts())\n"

# Correlation table

In [23]:
corr = train.corr()['bilissel_performans_skoru'].drop('bilissel_performans_skoru').sort_values(ascending=False)
print("Top 10 positive correlations:")
print(corr.head(10))
print("\nTop 10 negative correlations:")
print(corr.tail(10))

Top 10 positive correlations:
toplam_uyku_yuzdesi    0.469163
rem_yuzdesi            0.442999
meslek_target          0.395946
saglik_skoru           0.382966
gun_tipi               0.305426
derin_uyku_yuzdesi     0.280006
uyku_kalitesi_orani    0.258873
gunluk_adim_sayisi     0.134042
mevsim                 0.001276
cinsiyet               0.000310
Name: bilissel_performans_skoru, dtype: float64

Top 10 negative correlations:
yas                      -0.070659
dinlenik_nabiz_bpm       -0.089389
yasam_dengesi            -0.115475
uykuya_dalma_suresi_dk   -0.207349
gecelik_uyanma_sayisi    -0.270349
gece_bolunme_skoru       -0.320115
gunluk_calisma_saati     -0.342112
ruh_sagligi_durumu       -0.408300
stres_nabiz_etkilesimi   -0.559757
stres_skoru              -0.586676
Name: bilissel_performans_skoru, dtype: float64

In [24]:
from sklearn.metrics import root_mean_squared_error
import lightgbm as lgb
import xgboost as xgb
from sklearn.ensemble import RandomForestRegressor

# 3 ineffective columns dropped

In [25]:
cols_to_drop = ['kronotip', 'mevsim', 'cinsiyet']
X = train.drop(columns=['id', 'bilissel_performans_skoru'] + cols_to_drop)
y = train['bilissel_performans_skoru']
X_test = test.drop(columns=['id'] + cols_to_drop)
print(X.shape, y.shape, X_test.shape)

(56000, 26) (56000,) (24000, 26)

# Testing 3 new features (didn't work well)

In [26]:
"""# Remove the other two temporarily
cols_to_drop = ['kronotip', 'mevsim', 'cinsiyet', 'stres_uyku_etkilesimi', 'hafta_sonu_uyku_kalitesi']
X = train.drop(columns=['id', 'bilissel_performans_skoru'] + cols_to_drop)
y = train['bilissel_performans_skoru']
X_test = test.drop(columns=['id'] + cols_to_drop)

scores = cross_val_score(catboost_model, X, y, cv=kf, scoring='neg_root_mean_squared_error', n_jobs=-1)
print(f"CatBoost RMSE (only stres_ruh): {-scores.mean():.4f}")"""

'# Remove the other two temporarily\ncols_to_drop = [\'kronotip\', \'mevsim\', \'cinsiyet\', \'stres_uyku_etkilesimi\', \'hafta_sonu_uyku_kalitesi\']\nX = train.drop(columns=[\'id\', \'bilissel_performans_skoru\'] + cols_to_drop)\ny = train[\'bilissel_performans_skoru\']\nX_test = test.drop(columns=[\'id\'] + cols_to_drop)\n\nscores = cross_val_score(catboost_model, X, y, cv=kf, scoring=\'neg_root_mean_squared_error\', n_jobs=-1)\nprint(f"CatBoost RMSE (only stres_ruh): {-scores.mean():.4f}")'

In [27]:
"""# Test only hafta_sonu_uyku_kalitesi
cols_to_drop = ['kronotip', 'mevsim', 'cinsiyet', 'stres_uyku_etkilesimi', 'stres_ruh_etkilesimi']
X = train.drop(columns=['id', 'bilissel_performans_skoru'] + cols_to_drop)
y = train['bilissel_performans_skoru']
X_test = test.drop(columns=['id'] + cols_to_drop)

scores = cross_val_score(catboost_model, X, y, cv=kf, scoring='neg_root_mean_squared_error', n_jobs=-1)
print(f"CatBoost RMSE (only hafta_sonu_uyku_kalitesi): {-scores.mean():.4f}")

# Test only stres_uyku_etkilesimi
cols_to_drop = ['kronotip', 'mevsim', 'cinsiyet', 'hafta_sonu_uyku_kalitesi', 'stres_ruh_etkilesimi']
X = train.drop(columns=['id', 'bilissel_performans_skoru'] + cols_to_drop)
y = train['bilissel_performans_skoru']
X_test = test.drop(columns=['id'] + cols_to_drop)

scores = cross_val_score(catboost_model, X, y, cv=kf, scoring='neg_root_mean_squared_error', n_jobs=-1)
print(f"CatBoost RMSE (only stres_uyku): {-scores.mean():.4f}")"""

'# Test only hafta_sonu_uyku_kalitesi\ncols_to_drop = [\'kronotip\', \'mevsim\', \'cinsiyet\', \'stres_uyku_etkilesimi\', \'stres_ruh_etkilesimi\']\nX = train.drop(columns=[\'id\', \'bilissel_performans_skoru\'] + cols_to_drop)\ny = train[\'bilissel_performans_skoru\']\nX_test = test.drop(columns=[\'id\'] + cols_to_drop)\n\nscores = cross_val_score(catboost_model, X, y, cv=kf, scoring=\'neg_root_mean_squared_error\', n_jobs=-1)\nprint(f"CatBoost RMSE (only hafta_sonu_uyku_kalitesi): {-scores.mean():.4f}")\n\n# Test only stres_uyku_etkilesimi\ncols_to_drop = [\'kronotip\', \'mevsim\', \'cinsiyet\', \'hafta_sonu_uyku_kalitesi\', \'stres_ruh_etkilesimi\']\nX = train.drop(columns=[\'id\', \'bilissel_performans_skoru\'] + cols_to_drop)\ny = train[\'bilissel_performans_skoru\']\nX_test = test.drop(columns=[\'id\'] + cols_to_drop)\n\nscores = cross_val_score(catboost_model, X, y, cv=kf, scoring=\'neg_root_mean_squared_error\', n_jobs=-1)\nprint(f"CatBoost RMSE (only stres_uyku): {-scores.mean():.4f}")'

In [28]:
from catboost import CatBoostRegressor
from sklearn.model_selection import KFold, cross_val_score

# RMSE: 1.2248

In [29]:
"""
catboost = CatBoostRegressor(random_state=42, verbose=0)
scores = cross_val_score(catboost, X, y, cv=kf, scoring='neg_root_mean_squared_error', n_jobs=-1)
print(f"CatBoost RMSE: {-scores.mean():.4f} ± {scores.std():.4f}")"""

'\ncatboost = CatBoostRegressor(random_state=42, verbose=0)\nscores = cross_val_score(catboost, X, y, cv=kf, scoring=\'neg_root_mean_squared_error\', n_jobs=-1)\nprint(f"CatBoost RMSE: {-scores.mean():.4f} ± {scores.std():.4f}")'

In [30]:
"""
catboost_model = CatBoostRegressor(random_state=42, verbose=0)
catboost_model.fit(X, y)

lgbm_model = lgb.LGBMRegressor(
    random_state=42, verbose=-1,
    subsample=0.8, num_leaves=31,
    n_estimators=500, max_depth=5,
    learning_rate=0.05, colsample_bytree=0.8
)
lgbm_model.fit(X, y)

# Weighted average (CatBoost stronger so gets more weight)
cat_preds = catboost_model.predict(X_test)
lgbm_preds = lgbm_model.predict(X_test)

ensemble_preds = (0.6 * cat_preds) + (0.4 * lgbm_preds)

# Submission
submission = pd.DataFrame({
    'id': test['id'],
    'bilissel_performans_skoru': ensemble_preds
})
submission.to_csv('submission2.csv', index=False)
print(submission.head())
"""

"\ncatboost_model = CatBoostRegressor(random_state=42, verbose=0)\ncatboost_model.fit(X, y)\n\nlgbm_model = lgb.LGBMRegressor(\n    random_state=42, verbose=-1,\n    subsample=0.8, num_leaves=31,\n    n_estimators=500, max_depth=5,\n    learning_rate=0.05, colsample_bytree=0.8\n)\nlgbm_model.fit(X, y)\n\n# Weighted average (CatBoost stronger so gets more weight)\ncat_preds = catboost_model.predict(X_test)\nlgbm_preds = lgbm_model.predict(X_test)\n\nensemble_preds = (0.6 * cat_preds) + (0.4 * lgbm_preds)\n\n# Submission\nsubmission = pd.DataFrame({\n    'id': test['id'],\n    'bilissel_performans_skoru': ensemble_preds\n})\nsubmission.to_csv('submission2.csv', index=False)\nprint(submission.head())\n"

# Feature Importance

In [31]:
catboost_model = CatBoostRegressor(random_state=42, verbose=0)
catboost_model.fit(X, y)

importances = pd.Series(catboost_model.get_feature_importance(), index=X.columns)
print(importances.sort_values(ascending=False))

ruh_sagligi_durumu             16.143410
stres_skoru                    14.636132
toplam_uyku_yuzdesi            13.638626
gun_tipi                       11.595053
meslek_target                   8.607951
rem_yuzdesi                     6.836703
gece_bolunme_skoru              4.952763
saglik_skoru                    3.782414
gecelik_uyanma_sayisi           2.243182
stres_nabiz_etkilesimi          2.106075
oda_sicakligi_celsius           1.691129
uyku_kalitesi_orani             1.374544
gunluk_calisma_saati            1.171561
hafta_sonu_uyku_farki_saat      1.066710
yasam_dengesi                   1.007575
derin_uyku_yuzdesi              1.002852
vucut_kitle_indeksi             0.972883
gunluk_adim_sayisi              0.941022
yas                             0.937223
uyku_oncesi_ekran_suresi_dk     0.858094
kafein_ekran_etkilesimi         0.827524
ulke_target                     0.822780
sekerleme_suresi_dk             0.804342
dinlenik_nabiz_bpm              0.750413
uyku_oncesi_kafein_mg           0.684658
uykuya_dalma_suresi_dk          0.544380
dtype: float64

# RMSE: 1.2203

In [32]:
"""from sklearn.model_selection import RandomizedSearchCV

param_grid = {
    'iterations': [500, 1000, 2000],
    'learning_rate': [0.01, 0.03, 0.05, 0.1],
    'depth': [4, 6, 8, 10],
    'l2_leaf_reg': [1, 3, 5, 7],
    'subsample': [0.7, 0.8, 0.9],
    'colsample_bylevel': [0.7, 0.8, 0.9],
}

catboost = CatBoostRegressor(random_state=42, verbose=0)

search = RandomizedSearchCV(
    catboost, param_grid,
    n_iter=20,
    scoring='neg_root_mean_squared_error',
    cv=3,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

search.fit(X, y)

print(f"Best RMSE: {-search.best_score_:.4f}")
print(f"Best params: {search.best_params_}")"""

'from sklearn.model_selection import RandomizedSearchCV\n\nparam_grid = {\n    \'iterations\': [500, 1000, 2000],\n    \'learning_rate\': [0.01, 0.03, 0.05, 0.1],\n    \'depth\': [4, 6, 8, 10],\n    \'l2_leaf_reg\': [1, 3, 5, 7],\n    \'subsample\': [0.7, 0.8, 0.9],\n    \'colsample_bylevel\': [0.7, 0.8, 0.9],\n}\n\ncatboost = CatBoostRegressor(random_state=42, verbose=0)\n\nsearch = RandomizedSearchCV(\n    catboost, param_grid,\n    n_iter=20,\n    scoring=\'neg_root_mean_squared_error\',\n    cv=3,\n    random_state=42,\n    n_jobs=-1,\n    verbose=1\n)\n\nsearch.fit(X, y)\n\nprint(f"Best RMSE: {-search.best_score_:.4f}")\nprint(f"Best params: {search.best_params_}")'

In [33]:
"""best_catboost = CatBoostRegressor(
    random_state=42,
    verbose=0,
    subsample=0.9,
    learning_rate=0.05,
    l2_leaf_reg=7,
    iterations=500,
    depth=6,
    colsample_bylevel=0.8
)

best_catboost.fit(X, y)

predictions = best_catboost.predict(X_test)

submission = pd.DataFrame({
    'id': test['id'],
    'bilissel_performans_skoru': predictions
})

submission.to_csv('submission3.csv', index=False)
print(submission.head())"""

"best_catboost = CatBoostRegressor(\n    random_state=42,\n    verbose=0,\n    subsample=0.9,\n    learning_rate=0.05,\n    l2_leaf_reg=7,\n    iterations=500,\n    depth=6,\n    colsample_bylevel=0.8\n)\n\nbest_catboost.fit(X, y)\n\npredictions = best_catboost.predict(X_test)\n\nsubmission = pd.DataFrame({\n    'id': test['id'],\n    'bilissel_performans_skoru': predictions\n})\n\nsubmission.to_csv('submission3.csv', index=False)\nprint(submission.head())"

# RMSE: 1.2196, RMSE 2: 1.2185

In [34]:
"""from sklearn.model_selection import RandomizedSearchCV

param_grid = {
    'iterations': [500, 750, 1000],
    'learning_rate': [0.03, 0.05, 0.07],
    'depth': [5, 6, 7],
    'l2_leaf_reg': [5, 7, 9, 11],
    'subsample': [0.85, 0.9, 0.95],
    'colsample_bylevel': [0.75, 0.8, 0.85],
}

search2 = RandomizedSearchCV(
    CatBoostRegressor(random_state=42, verbose=0),
    param_grid,
    n_iter=20,
    scoring='neg_root_mean_squared_error',
    cv=3,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

search2.fit(X, y)

print(f"Best RMSE: {-search2.best_score_:.4f}")
print(f"Best params: {search2.best_params_}")"""

'from sklearn.model_selection import RandomizedSearchCV\n\nparam_grid = {\n    \'iterations\': [500, 750, 1000],\n    \'learning_rate\': [0.03, 0.05, 0.07],\n    \'depth\': [5, 6, 7],\n    \'l2_leaf_reg\': [5, 7, 9, 11],\n    \'subsample\': [0.85, 0.9, 0.95],\n    \'colsample_bylevel\': [0.75, 0.8, 0.85],\n}\n\nsearch2 = RandomizedSearchCV(\n    CatBoostRegressor(random_state=42, verbose=0),\n    param_grid,\n    n_iter=20,\n    scoring=\'neg_root_mean_squared_error\',\n    cv=3,\n    random_state=42,\n    n_jobs=-1,\n    verbose=1\n)\n\nsearch2.fit(X, y)\n\nprint(f"Best RMSE: {-search2.best_score_:.4f}")\nprint(f"Best params: {search2.best_params_}")'

# Best RMSE: 1.2194 old data,  Best RMSE 2: 1.2180

In [35]:
"""param_grid = {
    'iterations': [750, 1000, 1500],
    'learning_rate': [0.01, 0.02, 0.03],
    'depth': [5, 6, 7],
    'l2_leaf_reg': [5, 7, 9],
    'subsample': [0.85, 0.9, 0.95],
    'colsample_bylevel': [0.75, 0.8, 0.85],
}

search3 = RandomizedSearchCV(
    CatBoostRegressor(random_state=42, verbose=0),
    param_grid,
    n_iter=20,
    scoring='neg_root_mean_squared_error',
    cv=3,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

search3.fit(X, y)

print(f"Best RMSE: {-search3.best_score_:.4f}")
print(f"Best params: {search3.best_params_}")"""

'param_grid = {\n    \'iterations\': [750, 1000, 1500],\n    \'learning_rate\': [0.01, 0.02, 0.03],\n    \'depth\': [5, 6, 7],\n    \'l2_leaf_reg\': [5, 7, 9],\n    \'subsample\': [0.85, 0.9, 0.95],\n    \'colsample_bylevel\': [0.75, 0.8, 0.85],\n}\n\nsearch3 = RandomizedSearchCV(\n    CatBoostRegressor(random_state=42, verbose=0),\n    param_grid,\n    n_iter=20,\n    scoring=\'neg_root_mean_squared_error\',\n    cv=3,\n    random_state=42,\n    n_jobs=-1,\n    verbose=1\n)\n\nsearch3.fit(X, y)\n\nprint(f"Best RMSE: {-search3.best_score_:.4f}")\nprint(f"Best params: {search3.best_params_}")'

# RMSE: 1.2178 with %15-20 LightGBM & catboost

In [36]:
"""
kf = KFold(n_splits=5, shuffle=True, random_state=42)

cat_oof = np.zeros(len(X))
lgbm_oof = np.zeros(len(X))
cat_preds = np.zeros(len(X_test))
lgbm_preds = np.zeros(len(X_test))

for fold, (train_idx, val_idx) in enumerate(kf.split(X)):
    X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
    y_tr, y_val = y.iloc[train_idx], y.iloc[val_idx]

    # CatBoost
    cat = CatBoostRegressor(random_state=42, verbose=0,
        subsample=0.9, learning_rate=0.03, l2_leaf_reg=7,
        iterations=750, depth=6, colsample_bylevel=0.8)
    cat.fit(X_tr, y_tr)
    cat_oof[val_idx] = cat.predict(X_val)
    cat_preds += cat.predict(X_test) / 5

    # LightGBM
    lgbm = lgb.LGBMRegressor(random_state=42, verbose=-1,
        subsample=0.9, num_leaves=31, n_estimators=500,
        max_depth=5, learning_rate=0.05, colsample_bytree=0.8)
    lgbm.fit(X_tr, y_tr)
    lgbm_oof[val_idx] = lgbm.predict(X_val)
    lgbm_preds += lgbm.predict(X_test) / 5

# Try different weights
for cat_w in [0.5, 0.6, 0.7, 0.8]:
    lgbm_w = 1 - cat_w
    ensemble_oof = cat_w * cat_oof + lgbm_w * lgbm_oof
    rmse = np.sqrt(np.mean((ensemble_oof - y) ** 2))
    print(f"CatBoost {cat_w:.0%} + LightGBM {lgbm_w:.0%} → RMSE: {rmse:.4f}")

for cat_w in [0.8, 0.85, 0.9, 0.95, 1.0]:
    lgbm_w = 1 - cat_w
    ensemble_oof = cat_w * cat_oof + lgbm_w * lgbm_oof
    rmse = np.sqrt(np.mean((ensemble_oof - y) ** 2))
    print(f"CatBoost {cat_w:.0%} + LightGBM {lgbm_w:.0%} → RMSE: {rmse:.4f}")"""

'\nkf = KFold(n_splits=5, shuffle=True, random_state=42)\n\ncat_oof = np.zeros(len(X))\nlgbm_oof = np.zeros(len(X))\ncat_preds = np.zeros(len(X_test))\nlgbm_preds = np.zeros(len(X_test))\n\nfor fold, (train_idx, val_idx) in enumerate(kf.split(X)):\n    X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]\n    y_tr, y_val = y.iloc[train_idx], y.iloc[val_idx]\n\n    # CatBoost\n    cat = CatBoostRegressor(random_state=42, verbose=0,\n        subsample=0.9, learning_rate=0.03, l2_leaf_reg=7,\n        iterations=750, depth=6, colsample_bylevel=0.8)\n    cat.fit(X_tr, y_tr)\n    cat_oof[val_idx] = cat.predict(X_val)\n    cat_preds += cat.predict(X_test) / 5\n\n    # LightGBM\n    lgbm = lgb.LGBMRegressor(random_state=42, verbose=-1,\n        subsample=0.9, num_leaves=31, n_estimators=500,\n        max_depth=5, learning_rate=0.05, colsample_bytree=0.8)\n    lgbm.fit(X_tr, y_tr)\n    lgbm_oof[val_idx] = lgbm.predict(X_val)\n    lgbm_preds += lgbm.predict(X_test) / 5\n\n# Try different weights\nfor cat_w in [0.5, 0.6, 0.7, 0.8]:\n    lgbm_w = 1 - cat_w\n    ensemble_oof = cat_w * cat_oof + lgbm_w * lgbm_oof\n    rmse = np.sqrt(np.mean((ensemble_oof - y) ** 2))\n    print(f"CatBoost {cat_w:.0%} + LightGBM {lgbm_w:.0%} → RMSE: {rmse:.4f}")\n\nfor cat_w in [0.8, 0.85, 0.9, 0.95, 1.0]:\n    lgbm_w = 1 - cat_w\n    ensemble_oof = cat_w * cat_oof + lgbm_w * lgbm_oof\n    rmse = np.sqrt(np.mean((ensemble_oof - y) ** 2))\n    print(f"CatBoost {cat_w:.0%} + LightGBM {lgbm_w:.0%} → RMSE: {rmse:.4f}")'

In [37]:
"""ensemble_final = 0.8 * cat_preds + 0.2 * lgbm_preds

submission = pd.DataFrame({
    'id': test['id'],
    'bilissel_performans_skoru': ensemble_final
})

submission.to_csv('submission_lgb&catboost_1.csv', index=False)
print(submission.head())"""

"ensemble_final = 0.8 * cat_preds + 0.2 * lgbm_preds\n\nsubmission = pd.DataFrame({\n    'id': test['id'],\n    'bilissel_performans_skoru': ensemble_final\n})\n\nsubmission.to_csv('submission_lgb&catboost_1.csv', index=False)\nprint(submission.head())"

# TUNE LGBM

In [38]:
"""
param_grid = {
    'n_estimators': [500, 750, 1000],
    'learning_rate': [0.01, 0.03, 0.05],
    'max_depth': [5, 6, 7],
    'num_leaves': [31, 63, 127],
    'subsample': [0.8, 0.9, 0.95],
    'colsample_bytree': [0.7, 0.8, 0.9],
    'reg_alpha': [0, 0.1, 0.5],
    'reg_lambda': [0, 0.1, 0.5]
}

lgbm_search = RandomizedSearchCV(
    lgb.LGBMRegressor(random_state=42, verbose=-1),
    param_grid,
    n_iter=20,
    scoring='neg_root_mean_squared_error',
    cv=3,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

lgbm_search.fit(X, y)

print(f"Best RMSE: {-lgbm_search.best_score_:.4f}")
print(f"Best params: {lgbm_search.best_params_}")"""

'\nparam_grid = {\n    \'n_estimators\': [500, 750, 1000],\n    \'learning_rate\': [0.01, 0.03, 0.05],\n    \'max_depth\': [5, 6, 7],\n    \'num_leaves\': [31, 63, 127],\n    \'subsample\': [0.8, 0.9, 0.95],\n    \'colsample_bytree\': [0.7, 0.8, 0.9],\n    \'reg_alpha\': [0, 0.1, 0.5],\n    \'reg_lambda\': [0, 0.1, 0.5]\n}\n\nlgbm_search = RandomizedSearchCV(\n    lgb.LGBMRegressor(random_state=42, verbose=-1),\n    param_grid,\n    n_iter=20,\n    scoring=\'neg_root_mean_squared_error\',\n    cv=3,\n    random_state=42,\n    n_jobs=-1,\n    verbose=1\n)\n\nlgbm_search.fit(X, y)\n\nprint(f"Best RMSE: {-lgbm_search.best_score_:.4f}")\nprint(f"Best params: {lgbm_search.best_params_}")'

# COMBINE AGAIN WITH CAT, rmse: 1.2177

In [39]:
"""cat_oof2 = np.zeros(len(X))
lgbm_oof2 = np.zeros(len(X))
cat_preds2 = np.zeros(len(X_test))
lgbm_preds2 = np.zeros(len(X_test))

for fold, (train_idx, val_idx) in enumerate(kf.split(X)):
    X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
    y_tr, y_val = y.iloc[train_idx], y.iloc[val_idx]

    cat = CatBoostRegressor(random_state=42, verbose=0,
        subsample=0.9, learning_rate=0.03, l2_leaf_reg=7,
        iterations=750, depth=6, colsample_bylevel=0.8)
    cat.fit(X_tr, y_tr)
    cat_oof2[val_idx] = cat.predict(X_val)
    cat_preds2 += cat.predict(X_test) / 5

    lgbm = lgb.LGBMRegressor(random_state=42, verbose=-1,
        subsample=0.9, reg_lambda=0.1, reg_alpha=0.1,
        num_leaves=63, n_estimators=500, max_depth=5,
        learning_rate=0.03, colsample_bytree=0.7)
    lgbm.fit(X_tr, y_tr)
    lgbm_oof2[val_idx] = lgbm.predict(X_val)
    lgbm_preds2 += lgbm.predict(X_test) / 5

for cat_w in [0.7, 0.75, 0.8, 0.85, 0.9]:
    lgbm_w = 1 - cat_w
    ensemble_oof2 = cat_w * cat_oof2 + lgbm_w * lgbm_oof2
    rmse = np.sqrt(np.mean((ensemble_oof2 - y) ** 2))
    print(f"CatBoost {cat_w:.0%} + LightGBM {lgbm_w:.0%} → RMSE: {rmse:.4f}")"""

'cat_oof2 = np.zeros(len(X))\nlgbm_oof2 = np.zeros(len(X))\ncat_preds2 = np.zeros(len(X_test))\nlgbm_preds2 = np.zeros(len(X_test))\n\nfor fold, (train_idx, val_idx) in enumerate(kf.split(X)):\n    X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]\n    y_tr, y_val = y.iloc[train_idx], y.iloc[val_idx]\n\n    cat = CatBoostRegressor(random_state=42, verbose=0,\n        subsample=0.9, learning_rate=0.03, l2_leaf_reg=7,\n        iterations=750, depth=6, colsample_bylevel=0.8)\n    cat.fit(X_tr, y_tr)\n    cat_oof2[val_idx] = cat.predict(X_val)\n    cat_preds2 += cat.predict(X_test) / 5\n\n    lgbm = lgb.LGBMRegressor(random_state=42, verbose=-1,\n        subsample=0.9, reg_lambda=0.1, reg_alpha=0.1,\n        num_leaves=63, n_estimators=500, max_depth=5,\n        learning_rate=0.03, colsample_bytree=0.7)\n    lgbm.fit(X_tr, y_tr)\n    lgbm_oof2[val_idx] = lgbm.predict(X_val)\n    lgbm_preds2 += lgbm.predict(X_test) / 5\n\nfor cat_w in [0.7, 0.75, 0.8, 0.85, 0.9]:\n    lgbm_w = 1 - cat_w\n    ensemble_oof2 = cat_w * cat_oof2 + lgbm_w * lgbm_oof2\n    rmse = np.sqrt(np.mean((ensemble_oof2 - y) ** 2))\n    print(f"CatBoost {cat_w:.0%} + LightGBM {lgbm_w:.0%} → RMSE: {rmse:.4f}")'

In [40]:
"""ensemble_final2 = 0.75 * cat_preds2 + 0.25 * lgbm_preds2

submission = pd.DataFrame({
    'id': test['id'],
    'bilissel_performans_skoru': ensemble_final2
})

submission.to_csv('submission_lgbm&cat_2.csv', index=False)
print(submission.head())"""

"ensemble_final2 = 0.75 * cat_preds2 + 0.25 * lgbm_preds2\n\nsubmission = pd.DataFrame({\n    'id': test['id'],\n    'bilissel_performans_skoru': ensemble_final2\n})\n\nsubmission.to_csv('submission_lgbm&cat_2.csv', index=False)\nprint(submission.head())"